LAB 5 24 February 2026

Read the Colleges dataset and clean all the numeric attributes.
From all marks based attributes, remove % sign from different attributes. In SAT/ACT column, Keep higher value.
From all cost based attributes, Remove $ sign and commas.
Remove any null value in any attribute.

In [5]:
import pandas as pd

In [6]:
path ="Top 100 Private Colleges.2003.csv"
colleges = pd.read_csv(path)

colleges_copy = colleges.copy()

colleges.head()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21%,99/100%,3,71%,85%,10,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4
1,2,Rice University,TX,2787,24%,89/92%,5,68%,89%,19,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5
2,3,Williams College,MA,1985,23%,93/93%,8,89%,94%,1,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26
3,4,Swarthmore College,PA,1479,24%,94/98%,8,86%,92%,4,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21
4,5,Amherst College,MA,1618,18%,94/92%,9,84%,94%,5,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38

In [7]:
# remove % sign
def clean_percentage(value):
    if pd.isnull(value):
        return value
    return str(value).replace('%', '')

In [8]:
# remove $ and commas
def clean_cost(value):
    if pd.isnull(value):
        return value
    return str(value).replace('$', '').replace(',', '')

In [9]:
# keep higher value in SAT/ACT column
def clean_sat_act(value):
    if pd.isnull(value):
        return value

    parts = str(value).replace('/', ' ').split()
    numbers = []

    for p in parts:
        cleaned = ''.join(ch for ch in p if ch.isdigit())
        if cleaned != '':
            numbers.append(int(cleaned))

    if numbers:
        return max(numbers)

    return value

In [10]:
# cleaning
for col in colleges_copy.columns:
    
    # Percentage columns
    if colleges_copy[col].astype(str).str.contains('%', regex=False).any():
        print("%", col)
        colleges_copy[col] = colleges_copy[col].apply(clean_percentage)
    
    # Cost columns
    if colleges_copy[col].astype(str).str.contains('$', regex=False).any():
        print("$", col)
        colleges_copy[col] = colleges_copy[col].apply(clean_cost)
    
    # SAT/ACT columns
    if "SAT" in col or "ACT" in col:
        print("SAT", col)
        colleges_copy[col] = colleges_copy[col].apply(clean_sat_act)

% Admission Rate
% *SAT or ACT
SAT *SAT or ACT
% 4-year Grad. Rate
% 6-year Grad. Rate
$ Total Costs
$ Cost After Need-based Aid
% Need Met
% Aid From Grants
$ Cost After Non-Need-Based Aid
% Non-Need-Based Aid+
$ Average Debt

In [11]:
# convert string values to numeric after removal of dollar and so
for col in colleges_copy.columns:
    colleges_copy[col] = pd.to_numeric(colleges_copy[col], errors='ignore')

colleges_copy.isna().sum()

C:\Users\verma\AppData\Local\Temp\ipykernel_19760\3057994583.py:3: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  colleges_copy[col] = pd.to_numeric(colleges_copy[col], errors='ignore')

Overall Rank                      0
School                            0
State                             0
Undergrad. Enrollment             0
Admission Rate                    0
*SAT or ACT                       0
Student/faculty Ratio             0
4-year Grad. Rate                 0
6-year Grad. Rate                 0
Quality Rank                      0
Total Costs                       0
Cost After Need-based Aid         0
Need Met                          0
Aid From Grants                   0
Cost After Non-Need-Based Aid     0
Non-Need-Based Aid+              27
Average Debt                      0
Cost Rank                         0
dtype: int64

In [12]:
colleges_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Overall Rank                   100 non-null    int64
 1   School                         100 non-null    object
 2   State                          100 non-null    object
 3   Undergrad. Enrollment          100 non-null    int64
 4   Admission Rate                 100 non-null    int64
 5   *SAT or ACT                    100 non-null    int64
 6   Student/faculty Ratio          100 non-null    int64
 7   4-year Grad. Rate              100 non-null    int64
 8   6-year Grad. Rate              100 non-null    int64
 9   Quality Rank                   100 non-null    int64
 10  Total Costs                    100 non-null    int64
 11  Cost After Need-based Aid      100 non-null    int64
 12  Need Met                       100 non-null    object
 13  Aid From Grants                100 non-null    int64
 14  Cost After Non-Need-Based Aid  100 non-null    int64
 15  Non-Need-Based Aid+            73 non-null     float64
 16  Average Debt                   100 non-null    int64
 17  Cost Rank                      100 non-null    int64
dtypes: float64(1), int64(14), object(3)
memory usage: 14.2+ KB

In [13]:
print(len(colleges_copy))

100

In [14]:
# null values
colleges_copy = colleges_copy.dropna(axis=1, how="any")
print(len(colleges_copy))

100

In [15]:
colleges_copy.head(10)

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21,100,3,71,85,10,32682,10981,100,93,18553,10244,4
1,2,Rice University,TX,2787,24,92,5,68,89,19,28350,14779,100,88,22418,12705,5
2,3,Williams College,MA,1985,23,93,8,89,94,1,36550,14737,100,89,33251,12316,26
3,4,Swarthmore College,PA,1479,24,98,8,86,92,4,38676,17386,100,85,11404,12759,21
4,5,Amherst College,MA,1618,18,94,9,84,94,5,38492,14453,100,92,33411,11544,38
5,6,Webb Institute,NY,67,42,100,7,79,83,39,8079,5579,20,100,8079,5700,1
6,7,Yale University,CT,5339,8,97,7,88,95,3,38432,15729,100,89,38432,19228,53
7,8,Washington and Lee University,VA,1750,31,89,11,86,89,30,30225,15452,99,87,22063,15634,9
8,9,Harvard University,MA,6637,11,90,8,86,97,8,38831,17456,100,90,33201,10465,46
9,10,Stanford University,CA,7360,13,95,7,77,93,6,38875,17746,100,86,33709,15782,62

In [16]:
colleges_copy.to_csv("Cleaned_data.csv")

In [17]:
print(colleges_copy)

    Overall Rank                              School State  \
0              1  California Institute of Technology    CA
1              2                     Rice University    TX
2              3                    Williams College    MA
3              4                  Swarthmore College    PA
4              5                     Amherst College    MA
..           ...                                 ...   ...
95            96                      Babson College    MA
96            97       Rhode Island School of Design    RI
97            98    Rensselaer Polytechnic Institute    NY
98            99              Sarah Lawrence College    NY
99           100    The George Washington University    DC

    Undergrad. Enrollment  Admission Rate  *SAT or ACT  Student/faculty Ratio  \
0                     939              21          100                      3
1                    2787              24           92                      5
2                    1985              23           93                      8
3                    1479              24           98                      8
4                    1618              18           94                      9
..                    ...             ...          ...                    ...
95                   1735              48           77                     13
96                   1882              32           55                     11
97                   5139              70           92                     17
98                   1226              40           79                      6
99                  10328              40           72                     14

    4-year Grad. Rate  6-year Grad. Rate  Quality Rank  Total Costs  \
0                  71                 85            10        32682
1                  68                 89            19        28350
2                  89                 94             1        36550
3                  86                 92             4        38676
4                  84                 94             5        38492
..                ...                ...           ...          ...
95                 77                 81            77        38443
96                  0                 87            96        34472
97                 48                 75            84        39200
98                 51                 66            94        42121
99                 62                 73            98        40240

    Cost After Need-based Aid Need Met  Aid From Grants  \
0                       10981      100               93
1                       14779      100               88
2                       14737      100               89
3                       17386      100               85
4                       14453      100               92
..                        ...      ...              ...
95                      21316       98               78
96                      26447       69               53
97                      22360       90               74
98                      22847       94               73
99                      25866       94               56

    Cost After Non-Need-Based Aid  Average Debt  Cost Rank
0                           18553         10244          4
1                           22418         12705          5
2                           33251         12316         26
3                           11404         12759         21
4                           33411         11544         38
..                            ...           ...        ...
95                          30308             0         83
96                          33222         21125         80
97                          28411         24590         94
98                          33610         14864         89
99                          29916             0         96

[100 rows x 17 columns]