## Read the Colleges dataset and clean all the numeric attributes.

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"D:\College_work\ML\LAB_5\Top100_PrivateColleges2003.csv")
df.head()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Non-Need-Based Aid+,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21%,99/100%,3,71%,85%,10,"$32,682","$10,981",100%,93%,"$18,553",15%,"$10,244",4
1,2,Rice University,TX,2787,24%,89/92%,5,68%,89%,19,"$28,350","$14,779",100%,88%,"$22,418",34%,"$12,705",5
2,3,Williams College,MA,1985,23%,93/93%,8,89%,94%,1,"$36,550","$14,737",100%,89%,"$33,251",NaN,"$12,316",26
3,4,Swarthmore College,PA,1479,24%,94/98%,8,86%,92%,4,"$38,676","$17,386",100%,85%,"$11,404",2%,"$12,759",21
4,5,Amherst College,MA,1618,18%,94/92%,9,84%,94%,5,"$38,492","$14,453",100%,92%,"$33,411",NaN,"$11,544",38

In [49]:
len(df)

100

In [50]:
df.shape

(100, 18)

In [51]:
df.columns

Index(['Overall Rank', 'School', 'State', 'Undergrad. Enrollment',
       'Admission Rate', '*SAT or ACT', 'Student/faculty Ratio',
       '4-year Grad. Rate', '6-year Grad. Rate', 'Quality Rank', 'Total Costs',
       'Cost After Need-based Aid', 'Need Met', 'Aid From Grants',
       'Cost After Non-Need-Based Aid', 'Non-Need-Based Aid+', 'Average Debt',
       'Cost Rank'],
      dtype='object')

### Q3. Remove any null value in any attribute.

In [52]:
df.isnull().sum()/ len(df) *100

Overall Rank                      0.0
School                            0.0
State                             0.0
Undergrad. Enrollment             0.0
Admission Rate                    0.0
*SAT or ACT                       0.0
Student/faculty Ratio             0.0
4-year Grad. Rate                 0.0
6-year Grad. Rate                 0.0
Quality Rank                      0.0
Total Costs                       0.0
Cost After Need-based Aid         0.0
Need Met                          0.0
Aid From Grants                   0.0
Cost After Non-Need-Based Aid     0.0
Non-Need-Based Aid+              27.0
Average Debt                      0.0
Cost Rank                         0.0
dtype: float64

In [53]:
df = df.drop(columns=['Non-Need-Based Aid+'])

In [54]:
df.isnull().sum()/ len(df) *100

Overall Rank                     0.0
School                           0.0
State                            0.0
Undergrad. Enrollment            0.0
Admission Rate                   0.0
*SAT or ACT                      0.0
Student/faculty Ratio            0.0
4-year Grad. Rate                0.0
6-year Grad. Rate                0.0
Quality Rank                     0.0
Total Costs                      0.0
Cost After Need-based Aid        0.0
Need Met                         0.0
Aid From Grants                  0.0
Cost After Non-Need-Based Aid    0.0
Average Debt                     0.0
Cost Rank                        0.0
dtype: float64

### Q1. From all marks based attributes, remove % sign from different attributes. In SAT/ACT column, Keep higher value.

In [55]:
def percentage_removal(value):
    if pd.isnull(value):
        return value

    value = str(value).strip()

    if '%' in value:
        return value.replace('%','')

    if '/' in value:  # case like 99/100
        num, den = value.split('/')
        return (float(num)/float(den))*100

    return value


for col in df.columns:
    if df[col].astype(str).str.contains('%').any():
        df[col] = df[col].apply(percentage_removal)

df.head()

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21,99/100,3,71,85,10,"$32,682","$10,981",100,93,"$18,553","$10,244",4
1,2,Rice University,TX,2787,24,89/92,5,68,89,19,"$28,350","$14,779",100,88,"$22,418","$12,705",5
2,3,Williams College,MA,1985,23,93/93,8,89,94,1,"$36,550","$14,737",100,89,"$33,251","$12,316",26
3,4,Swarthmore College,PA,1479,24,94/98,8,86,92,4,"$38,676","$17,386",100,85,"$11,404","$12,759",21
4,5,Amherst College,MA,1618,18,94/92,9,84,94,5,"$38,492","$14,453",100,92,"$33,411","$11,544",38

In [ ]:
import re

def clean_sat_act(value):
    if pd.isna(value):
        return None

    value = str(value)

    numbers = re.findall(r'\d+', value)   

    if numbers:
        numbers = [int(n) for n in numbers]
        return max(numbers)

    return None

df['*SAT or ACT'] = df['*SAT or ACT'].apply(clean_sat_act)
df.head(10)

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21,100,3,71,85,10,"$32,682","$10,981",100,93,"$18,553","$10,244",4
1,2,Rice University,TX,2787,24,92,5,68,89,19,"$28,350","$14,779",100,88,"$22,418","$12,705",5
2,3,Williams College,MA,1985,23,93,8,89,94,1,"$36,550","$14,737",100,89,"$33,251","$12,316",26
3,4,Swarthmore College,PA,1479,24,98,8,86,92,4,"$38,676","$17,386",100,85,"$11,404","$12,759",21
4,5,Amherst College,MA,1618,18,94,9,84,94,5,"$38,492","$14,453",100,92,"$33,411","$11,544",38
5,6,Webb Institute,NY,67,42,100,7,79,83,39,"$8,079","$5,579",20,100,"$8,079","$5,700",1
6,7,Yale University,CT,5339,8,97,7,88,95,3,"$38,432","$15,729",100,89,"$38,432","$19,228",53
7,8,Washington and Lee University,VA,1750,31,89,11,86,89,30,"$30,225","$15,452",99,87,"$22,063","$15,634",9
8,9,Harvard University,MA,6637,11,90,8,86,97,8,"$38,831","$17,456",100,90,"$33,201","$10,465",46
9,10,Stanford University,CA,7360,13,95,7,77,93,6,"$38,875","$17,746",100,86,"$33,709","$15,782",62

### Q2. From all cost based attributes, Remove $ sign and commas.

In [58]:
def clean_dollar(value):
    if pd.isnull(value):
        return value
    
    value = str(value)
    value = value.replace('$','').replace(',','')
    return value

for col in df.columns:
    if df[col].astype(str).str.contains('\$').any():
        df[col] = df[col].apply(clean_dollar)

df.head(10)

<>:10: SyntaxWarning: invalid escape sequence '\$'
<>:10: SyntaxWarning: invalid escape sequence '\$'
C:\Users\Asus\AppData\Local\Temp\ipykernel_30452\2664325170.py:10: SyntaxWarning: invalid escape sequence '\$'
  if df[col].astype(str).str.contains('\$').any():

,Overall Rank,School,State,Undergrad. Enrollment,Admission Rate,*SAT or ACT,Student/faculty Ratio,4-year Grad. Rate,6-year Grad. Rate,Quality Rank,Total Costs,Cost After Need-based Aid,Need Met,Aid From Grants,Cost After Non-Need-Based Aid,Average Debt,Cost Rank
0,1,California Institute of Technology,CA,939,21,100,3,71,85,10,32682,10981,100,93,18553,10244,4
1,2,Rice University,TX,2787,24,92,5,68,89,19,28350,14779,100,88,22418,12705,5
2,3,Williams College,MA,1985,23,93,8,89,94,1,36550,14737,100,89,33251,12316,26
3,4,Swarthmore College,PA,1479,24,98,8,86,92,4,38676,17386,100,85,11404,12759,21
4,5,Amherst College,MA,1618,18,94,9,84,94,5,38492,14453,100,92,33411,11544,38
5,6,Webb Institute,NY,67,42,100,7,79,83,39,8079,5579,20,100,8079,5700,1
6,7,Yale University,CT,5339,8,97,7,88,95,3,38432,15729,100,89,38432,19228,53
7,8,Washington and Lee University,VA,1750,31,89,11,86,89,30,30225,15452,99,87,22063,15634,9
8,9,Harvard University,MA,6637,11,90,8,86,97,8,38831,17456,100,90,33201,10465,46
9,10,Stanford University,CA,7360,13,95,7,77,93,6,38875,17746,100,86,33709,15782,62