### Learning and practining about pandas

In [6]:
import numpy as np
import pandas as pd

array = np.ones(5, dtype=([('first', int), ('second','U4'), ('third',float)]))
print(array)
print(array.shape)
print(array['first'])
print(array['second'])
print(array['third'])
print(array['first']+ array['third'])

[(1, '1', 1.) (1, '1', 1.) (1, '1', 1.) (1, '1', 1.) (1, '1', 1.)]
(5,)
[1 1 1 1 1]
['1' '1' '1' '1' '1']
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]

In [ ]:
b = array.view(np.recarray)
print(b)
print(b.first)
print(b.second[3])
print(type(b.third))
print(type(b.third[2]))
print(b.third) # there is a difference between them here 
print(array['third'])

[(1, '1', 1.) (1, '1', 1.) (1, '1', 1.) (1, '1', 1.) (1, '1', 1.)]
[1 1 1 1 1]
1
<class 'numpy.ndarray'>
<class 'numpy.float64'>
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]

In [ ]:
# now talking about 
# series - one dimensional array with fixed length
# and 
# dataframe - 2d array , fixed length

s = pd.Series([1,2,3,np.nan,4,5.8,'kid'])
print(s) # if you are taking any value of dtype:object then it will automatically convert the complete series as object
print()
s2 = pd.Series([3,4,np.nan, 8,0.9,np.nan])
print(s2) # dtype become float

0      1
1      2
2      3
3    NaN
4      4
5    5.8
6    kid
dtype: object

0    3.0
1    4.0
2    NaN
3    8.0
4    0.9
5    NaN
dtype: float64

In [32]:
dates = pd.date_range('20041225',periods=20)
print(dates)

print(dates.year)
print(dates.month)
print(dates.day)

DatetimeIndex(['2004-12-25', '2004-12-26', '2004-12-27', '2004-12-28',
               '2004-12-29', '2004-12-30', '2004-12-31', '2005-01-01',
               '2005-01-02', '2005-01-03', '2005-01-04', '2005-01-05',
               '2005-01-06', '2005-01-07', '2005-01-08', '2005-01-09',
               '2005-01-10', '2005-01-11', '2005-01-12', '2005-01-13'],
              dtype='datetime64[ns]', freq='D')
Index([2004, 2004, 2004, 2004, 2004, 2004, 2004, 2005, 2005, 2005, 2005, 2005,
       2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005],
      dtype='int32')
Index([12, 12, 12, 12, 12, 12, 12, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype='int32')
Index([25, 26, 27, 28, 29, 30, 31, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], dtype='int32')

In [41]:
# len(dates)
dates.shape[0]

20

In [ ]:
# creating dataframe using dictionary
df = pd.DataFrame(np.random.randn(20,6), index=dates, columns=list('ABCDEF'))
print(df) 
# the values inside the randn function should be 
# row = dates.shape[0] or len(dates)
# col = len(list)

                   A         B         C         D         E         F
2004-12-25  0.901178  1.183993 -0.665985 -1.251340  0.789552 -1.072988
2004-12-26  1.584543  1.098517  0.090894 -0.794879 -1.366482 -0.294890
2004-12-27  1.108852 -2.606354 -0.257280 -1.662604  0.133725  0.557110
2004-12-28 -0.598715 -0.644262 -1.448432 -2.328734 -0.077005  0.503369
2004-12-29  0.313204 -0.810369 -0.600397 -0.220551  0.085170  0.664866
2004-12-30 -0.039122  0.657096  1.980081  0.298763  1.596275 -0.570858
2004-12-31 -0.720733  0.679850 -1.478718 -0.734037 -0.586681  1.057813
2005-01-01  0.066604 -0.705119 -0.996864 -0.097455  0.000284  0.726360
2005-01-02 -0.687294  0.582324 -0.912948 -0.668665 -0.488302 -0.756171
2005-01-03  0.698169  0.708157 -0.893956 -1.139124  0.273123  0.853943
2005-01-04 -0.793065  0.628159 -1.523942 -1.392774 -0.719160  1.713721
2005-01-05  1.052088 -0.299608 -0.404096 -0.034048 -0.475428 -0.245774
2005-01-06  0.210123 -0.348842 -1.316445 -0.099832 -0.803268 -0.784656
2005-01-07  0.419319 -0.848021 -0.558316 -0.266410 -0.986954 -0.312920
2005-01-08  0.591640 -0.323011  0.594921  0.457728 -0.051501 -1.621947
2005-01-09  0.829267 -0.362152  0.113976  0.004407  0.371633 -1.075252
2005-01-10  0.055697  0.389957 -0.360645 -0.948414  0.102535 -0.324339
2005-01-11 -0.162119 -0.032898 -0.024974 -0.614931  0.376040  0.458146
2005-01-12  0.887885 -0.772647  0.528212 -2.029645  2.293401  0.028772
2005-01-13  2.014541 -1.402390 -0.840160 -2.874439  1.448563  2.088903

In [55]:
# creating dataframe from np.array

data = np.array([['','Col1','Col2'],['Row1',1,2],['Row2',3,4]])
print(data)
print(type(data))
print(data[0])
print(type(data[0]))
print(data[0][0])
print(type(data[0][0]))
print(data[2][1])
print(type(data[2][1]))

[['' 'Col1' 'Col2']
 ['Row1' '1' '2']
 ['Row2' '3' '4']]
<class 'numpy.ndarray'>
['' 'Col1' 'Col2']
<class 'numpy.ndarray'>

<class 'numpy.str_'>
3
<class 'numpy.str_'>

In [66]:
df = pd.DataFrame(data = data[1:,1:], index = data[1:,0],columns=data[0,1:])
print(df.index)
print(df.columns)
print()
print(df)
type(print())

Index(['Row1', 'Row2'], dtype='object')
Index(['Col1', 'Col2'], dtype='object')

     Col1 Col2
Row1    1    2
Row2    3    4

NoneType

In [67]:
df = pd.DataFrame(data = data)
print(df.index)
print(df.columns)
print(df)

RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=3, step=1)
      0     1     2
0        Col1  Col2
1  Row1     1     2
2  Row2     3     4

In [72]:
data_val = [[1,2,3],[4,5,6],[7,8,9]]
data_df = pd.DataFrame(data = data_val, index = range(100,103), columns=['A','B','D'])
print(data_df)
# same case , row = range value/array of size data_val.shape[0] , col = columns value

     A  B  D
100  1  2  3
101  4  5  6
102  7  8  9

Accessing elements of dataframe

In [91]:
print(data_df.iloc[0,2]) # gives the value , works like matrix indexing
print(data_df.iat[0,2]) # gives the value , works like matrix indexing


print(data_df.loc[100:101,'A':'D']) # need to take the row value and the column value such that at 100 th row and A col value = ?
print(data_df.loc[102,'D'])
print(data_df.at[102,'D'])

# at and iat are faster because they only give one single value

3
3
     A  B  D
100  1  2  3
101  4  5  6
9
9

In [98]:
data_df['C'] = data_df['A']
data_df['E'] = data_df.index
print(data_df)
print(data_df.shape)

     A  B  D  C    E
100  1  2  3  1  100
101  4  5  6  4  101
102  7  8  9  7  102
(3, 5)

In [101]:
# deleting the column
# data_df.drop('D', axis=1, inplace=True)
data_df

     A  B  C    E
100  1  2  1  100
101  4  5  4  101
102  7  8  7  102

Combining data frame

In [110]:
Eno=[100, 101,102, 103, 104,105]
Empname= ['Raja', 'Babu', 'Kumar','Karthik','Rajesh','Raju']

Eno_series = pd.Series(Eno)
Emp_series = pd.Series(Empname)

df = {'Eno' :Eno_series,'Empname':Emp_series}
employee1 = pd.DataFrame(df)

(employee1)

   Eno  Empname
0  100     Raja
1  101     Babu
2  102    Kumar
3  103  Karthik
4  104   Rajesh
5  105     Raju

In [111]:
Eno1=[106, 107,108, 109, 110]
Empname1= ['Jack', 'John', 'Peter','David','Davis']
Eno_Series1 = pd.Series(Eno1)
Empname_Series1 = pd.Series(Empname1)
df = { 'Eno': Eno_Series1, 'Empname': Empname_Series1 }
employee2 = pd.DataFrame(df)
employee2

   Eno Empname
0  106    Jack
1  107    John
2  108   Peter
3  109   David
4  110   Davis

In [112]:
df_concat = pd.concat([employee1,employee2], ignore_index=True)
df_concat

    Eno  Empname
0   100     Raja
1   101     Babu
2   102    Kumar
3   103  Karthik
4   104   Rajesh
5   105     Raju
6   106     Jack
7   107     John
8   108    Peter
9   109    David
10  110    Davis

In [116]:
coll = [employee1, employee2]

df_con_key = pd.concat(coll, keys=['Section-A','Section-B'])
print(df_con_key)

             Eno  Empname
Section-A 0  100     Raja
          1  101     Babu
          2  102    Kumar
          3  103  Karthik
          4  104   Rajesh
          5  105     Raju
Section-B 0  106     Jack
          1  107     John
          2  108    Peter
          3  109    David
          4  110    Davis