In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
vehicle = pd.read_csv("vehicle.csv")
vehicle.head()

,compactness,circularity,distance circularity,radius ratio,pr.axis aspect ratio,max.length aspect ratio,scatter ratio,elongatedness,pr.axis rectangularity,max.length rectangularity,scaled variance along major axis,scaled variance along minor axis,scaled radius of gyration,skewness about major axis,skewness about minor axis,kurtosis about minor axis,kurtosis about major axis,hollows ratio,vehicle
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [5]:
vehicle.tail(4)

,compactness,circularity,distance circularity,radius ratio,pr.axis aspect ratio,max.length aspect ratio,scatter ratio,elongatedness,pr.axis rectangularity,max.length rectangularity,scaled variance along major axis,scaled variance along minor axis,scaled radius of gyration,skewness about major axis,skewness about minor axis,kurtosis about minor axis,kurtosis about major axis,hollows ratio,vehicle
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,van
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,saab
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,saab
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,van

In [4]:
vehicle.columns

Index(['compactness', 'circularity', 'distance circularity', 'radius ratio',
       'pr.axis aspect ratio', 'max.length aspect ratio', 'scatter ratio',
       'elongatedness', 'pr.axis rectangularity', 'max.length rectangularity',
       'scaled variance along major axis', 'scaled variance along minor axis',
       'scaled radius of gyration', 'skewness about major axis',
       'skewness about minor axis', 'kurtosis about minor axis',
       'kurtosis about major axis', 'hollows ratio', 'vehicle'],
      dtype='object')

In [6]:
vehicle.index

RangeIndex(start=0, stop=846, step=1)

In [7]:
vehicle.values

array([[95, 48, 83, ..., 187, 197, 'van'],
       [91, 41, 84, ..., 189, 199, 'van'],
       [104, 50, 106, ..., 188, 196, 'saab'],
       ...,
       [106, 54, 101, ..., 187, 201, 'saab'],
       [86, 36, 78, ..., 190, 195, 'saab'],
       [85, 36, 66, ..., 186, 190, 'van']], dtype=object)

In [9]:
vehicle.describe()

,compactness,circularity,distance circularity,radius ratio,pr.axis aspect ratio,max.length aspect ratio,scatter ratio,elongatedness,pr.axis rectangularity,max.length rectangularity,scaled variance along major axis,scaled variance along minor axis,scaled radius of gyration,skewness about major axis,skewness about minor axis,kurtosis about minor axis,kurtosis about major axis,hollows ratio
count,846.000000,846.000000,846.000000,846.000000,846.000000,846.000000,846.000000,846.000000,846.000000,846.000000,846.000000,846.000000,846.00000,846.000000,846.000000,846.000000,846.000000,846.000000
mean,93.678487,44.861702,82.088652,168.940898,61.693853,8.567376,168.839243,40.933806,20.582742,147.998818,188.625296,439.911348,174.70331,72.462175,6.377069,12.599291,188.932624,195.632388
std,8.234474,6.169866,15.771533,33.472183,7.888251,4.601217,33.244978,7.811560,2.592138,14.515652,31.394837,176.692614,32.54649,7.486974,4.918353,8.931240,6.163949,7.438797
min,73.000000,33.000000,40.000000,104.000000,47.000000,2.000000,112.000000,26.000000,17.000000,118.000000,130.000000,184.000000,109.00000,59.000000,0.000000,0.000000,176.000000,181.000000
25%,87.000000,40.000000,70.000000,141.000000,57.000000,7.000000,146.250000,33.000000,19.000000,137.000000,167.000000,318.250000,149.00000,67.000000,2.000000,5.000000,184.000000,190.250000
50%,93.000000,44.000000,80.000000,167.000000,61.000000,8.000000,157.000000,43.000000,20.000000,146.000000,178.500000,364.000000,173.00000,71.500000,6.000000,11.000000,188.000000,197.000000
75%,100.000000,49.000000,98.000000,195.000000,65.000000,10.000000,198.000000,46.000000,23.000000,159.000000,217.000000,587.000000,198.00000,75.000000,9.000000,19.000000,193.000000,201.000000
max,119.000000,59.000000,112.000000,333.000000,138.000000,55.000000,265.000000,61.000000,29.000000,188.000000,320.000000,1018.000000,268.00000,135.000000,22.000000,41.000000,206.000000,211.000000

In [11]:
vehicle[0:3]

,compactness,circularity,distance circularity,radius ratio,pr.axis aspect ratio,max.length aspect ratio,scatter ratio,elongatedness,pr.axis rectangularity,max.length rectangularity,scaled variance along major axis,scaled variance along minor axis,scaled radius of gyration,skewness about major axis,skewness about minor axis,kurtosis about minor axis,kurtosis about major axis,hollows ratio,vehicle
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab

In [12]:
vehicle[15:20]

,compactness,circularity,distance circularity,radius ratio,pr.axis aspect ratio,max.length aspect ratio,scatter ratio,elongatedness,pr.axis rectangularity,max.length rectangularity,scaled variance along major axis,scaled variance along minor axis,scaled radius of gyration,skewness about major axis,skewness about minor axis,kurtosis about minor axis,kurtosis about major axis,hollows ratio,vehicle
15,96,55,103,201,65,9,204,32,23,166,227,624,246,74,6,2,186,194,opel
16,89,36,51,109,52,6,118,57,17,129,137,206,125,80,2,14,181,185,van
17,99,41,77,197,69,6,177,36,21,139,202,485,151,72,4,10,198,199,bus
18,104,54,100,186,61,10,216,31,24,173,225,686,220,74,5,11,185,195,saab
19,101,56,100,215,69,10,208,32,24,169,227,651,223,74,6,5,186,193,opel

In [18]:
vehicle["vehicle"]

0       van
1       van
2      saab
3       van
4       bus
       ...
841    saab
842     van
843    saab
844    saab
845     van
Name: vehicle, Length: 846, dtype: object

Position based

In [19]:
vehicle.loc[0:10,['compactness','radius ratio','vehicle']]

    compactness  radius ratio vehicle
0            95           178     van
1            91           141     van
2           104           209    saab
3            93           159     van
4            85           205     bus
5           107           172     bus
6            97           173     bus
7            90           157     van
8            86           140     van
9            93           197    saab
10           86           143     van

In [ ]:
vehicle.iloc[10:20][:] #for all

,compactness,circularity,distance circularity,radius ratio,pr.axis aspect ratio,max.length aspect ratio,scatter ratio,elongatedness,pr.axis rectangularity,max.length rectangularity,scaled variance along major axis,scaled variance along minor axis,scaled radius of gyration,skewness about major axis,skewness about minor axis,kurtosis about minor axis,kurtosis about major axis,hollows ratio,vehicle
10,86,36,70,143,61,9,133,50,18,130,153,266,127,66,2,10,194,202,van
11,90,34,66,136,55,6,123,54,17,118,148,224,118,65,5,26,196,202,saab
12,88,46,74,171,68,6,152,43,19,148,180,349,192,71,5,11,189,195,bus
13,89,42,85,144,58,10,152,44,19,144,173,345,161,72,8,13,187,197,van
14,94,49,79,203,71,5,174,37,21,154,196,465,206,71,6,2,197,199,bus
15,96,55,103,201,65,9,204,32,23,166,227,624,246,74,6,2,186,194,opel
16,89,36,51,109,52,6,118,57,17,129,137,206,125,80,2,14,181,185,van
17,99,41,77,197,69,6,177,36,21,139,202,485,151,72,4,10,198,199,bus
18,104,54,100,186,61,10,216,31,24,173,225,686,220,74,5,11,185,195,saab
19,101,56,100,215,69,10,208,32,24,169,227,651,223,74,6,5,186,193,opel

In [28]:
vehicle.iloc[10:20,4:8]

,pr.axis aspect ratio,max.length aspect ratio,scatter ratio,elongatedness
10,61,9,133,50
11,55,6,123,54
12,68,6,152,43
13,58,10,152,44
14,71,5,174,37
15,65,9,204,32
16,52,6,118,57
17,69,6,177,36
18,61,10,216,31
19,69,10,208,32

In [31]:
col = ["compactness","vehicle"]
vehicle.iloc[10:20][col]

    compactness vehicle
10           86     van
11           90    saab
12           88     bus
13           89     van
14           94     bus
15           96    opel
16           89     van
17           99     bus
18          104    saab
19          101    opel

Reshaping Dataframe

In [32]:

IPL_Team = {'Team': ['CSK', 'RCB', 'KKR', 'MUMBAI INDIANS', 'SRH',
'Punjab Kings', 'RR', 'DELHI CAPITALS', 'CSK', 'RCB', 'KKR', 'MUMBAI INDIANS', 'SRH',
'Punjab Kings', 'RR', 'DELHI CAPITALS','CSK', 'RCB', 'KKR', 'MUMBAI INDIANS', 'SRH',
'Punjab Kings', 'RR', 'DELHI CAPITALS'],
'Year': [2018,2018,2018,2018,2018,2018,2018,2018,2019,2019,2019,2019,2019,2019,2019,2019,2020,2020,2020,2020,2020,2020,2020,2020],
'Points':[23,43,45,65,76,34,23,78,89,76,92,87,50,45,67,89,89,76,92,87,43,24,32,85]}

ipl_team_df = pd.DataFrame(IPL_Team)
ipl_team_df

              Team  Year  Points
0              CSK  2018      23
1              RCB  2018      43
2              KKR  2018      45
3   MUMBAI INDIANS  2018      65
4              SRH  2018      76
5     Punjab Kings  2018      34
6               RR  2018      23
7   DELHI CAPITALS  2018      78
8              CSK  2019      89
9              RCB  2019      76
10             KKR  2019      92
11  MUMBAI INDIANS  2019      87
12             SRH  2019      50
13    Punjab Kings  2019      45
14              RR  2019      67
15  DELHI CAPITALS  2019      89
16             CSK  2020      89
17             RCB  2020      76
18             KKR  2020      92
19  MUMBAI INDIANS  2020      87
20             SRH  2020      43
21    Punjab Kings  2020      24
22              RR  2020      32
23  DELHI CAPITALS  2020      85

1. Groupby

In [35]:
group_df = ipl_team_df.groupby("Team")

for t , g in group_df :
    print(f"--- {t} --- ")
    print(g)
    print()

--- CSK ---
   Team  Year  Points
0   CSK  2018      23
8   CSK  2019      89
16  CSK  2020      89

--- DELHI CAPITALS ---
              Team  Year  Points
7   DELHI CAPITALS  2018      78
15  DELHI CAPITALS  2019      89
23  DELHI CAPITALS  2020      85

--- KKR ---
   Team  Year  Points
2   KKR  2018      45
10  KKR  2019      92
18  KKR  2020      92

--- MUMBAI INDIANS ---
              Team  Year  Points
3   MUMBAI INDIANS  2018      65
11  MUMBAI INDIANS  2019      87
19  MUMBAI INDIANS  2020      87

--- Punjab Kings ---

            Team  Year  Points
5   Punjab Kings  2018      34
13  Punjab Kings  2019      45
21  Punjab Kings  2020      24

--- RCB ---
   Team  Year  Points
1   RCB  2018      43
9   RCB  2019      76
17  RCB  2020      76

--- RR ---
   Team  Year  Points
6    RR  2018      23
14   RR  2019      67
22   RR  2020      32

--- SRH ---
   Team  Year  Points
4   SRH  2018      76
12  SRH  2019      50
20  SRH  2020      43

In [36]:
group_df = ipl_team_df.groupby("Year")

for t , g in group_df :
    print(f"--- {t} --- ")
    print(g)
    print()

--- 2018 ---
             Team  Year  Points
0             CSK  2018      23
1             RCB  2018      43
2             KKR  2018      45
3  MUMBAI INDIANS  2018      65
4             SRH  2018      76
5    Punjab Kings  2018      34
6              RR  2018      23
7  DELHI CAPITALS  2018      78

--- 2019 ---
              Team  Year  Points
8              CSK  2019      89
9              RCB  2019      76
10             KKR  2019      92
11  MUMBAI INDIANS  2019      87
12             SRH  2019      50
13    Punjab Kings  2019      45
14              RR  2019      67
15  DELHI CAPITALS  2019      89

--- 2020 ---
              Team  Year  Points
16             CSK  2020      89
17             RCB  2020      76
18             KKR  2020      92
19  MUMBAI INDIANS  2020      87
20             SRH  2020      43
21    Punjab Kings  2020      24
22              RR  2020      32
23  DELHI CAPITALS  2020      85

In [37]:
group_df

2. Transpose

In [39]:
ipl_team_df.T

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
Team,CSK,RCB,KKR,MUMBAI INDIANS,SRH,Punjab Kings,RR,DELHI CAPITALS,CSK,RCB,...,RR,DELHI CAPITALS,CSK,RCB,KKR,MUMBAI INDIANS,SRH,Punjab Kings,RR,DELHI CAPITALS
Year,2018,2018,2018,2018,2018,2018,2018,2018,2019,2019,...,2019,2019,2020,2020,2020,2020,2020,2020,2020,2020
Points,23,43,45,65,76,34,23,78,89,76,...,67,89,89,76,92,87,43,24,32,85

Doubt = we used to write label encoder or can we use category encode , which one to use and why?

In [40]:
data=pd.DataFrame(
    {"Fruits":["Apple","Banana","Cherries","Grapes","Mango","Banana","Cherries","Grapes","Mango","Apple"]}
    )
data

     Fruits
0     Apple
1    Banana
2  Cherries
3    Grapes
4     Mango
5    Banana
6  Cherries
7    Grapes
8     Mango
9     Apple

In [48]:
import category_encoders as ce    
encoder = ce.OneHotEncoder(
    cols='Fruits',
    handle_unknown='return_nan',
    return_df=True,
    use_cat_names=True
)

data_encoder = encoder.fit_transform(data)
data_encoder

   Fruits_Apple  Fruits_Banana  Fruits_Cherries  Fruits_Grapes  Fruits_Mango
0           1.0            0.0              0.0            0.0           0.0
1           0.0            1.0              0.0            0.0           0.0
2           0.0            0.0              1.0            0.0           0.0
3           0.0            0.0              0.0            1.0           0.0
4           0.0            0.0              0.0            0.0           1.0
5           0.0            1.0              0.0            0.0           0.0
6           0.0            0.0              1.0            0.0           0.0
7           0.0            0.0              0.0            1.0           0.0
8           0.0            0.0              0.0            0.0           1.0
9           1.0            0.0              0.0            0.0           0.0

In [47]:
!pip install category_encoders

Defaulting to user installation because normal site-packages is not writeable
Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in d:\program\lib\site-packages (from category_encoders) (1.26.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from category_encoders) (2.2.3)
Requirement already satisfied: patsy>=0.5.1 in d:\program\lib\site-packages (from category_encoders) (0.5.6)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from category_encoders) (1.15.0rc2)
Requirement already satisfied: statsmodels>=0.9.0 in d:\program\lib\site-packages (from category_encoders) (0.14.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: six in c:\users\asus\appdata\roaming\python\python312\site-packages (from patsy>=0.5.1->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\asus\appdata\roaming\python\python312\site-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

[notice] A new release of pip is available: 25.1.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip